Bug 1680474- Join on the dispatcher thread after shutting it down
mozilla/glean pull request #1362
Opened 2020-12-04 13:44 UTC by Dexterp37

This makes sure tools (e.g. TSAN) properly account for the thread being shut down and do not flag this as a pending
thread error.

2020-12-04 13:48 UTC, badboy commented on glean-core/rlb/src/dispatcher/global.rs
> +        .unwrap()
```suggestion
    let dispatcher = GLOBAL_DISPATCHER
        .write()
        .unwrap()
        .as_mut()
        .expect("Global dispatcher has gone missing");
      
    if let Some(worker) = dispatcher.worker.take() {
        return worker.join().map_err(|_| DispatchError::WorkerPanic);
    }
    
    Ok(())
```

2020-12-04 14:45 UTC, Dexterp37 commented
@badboy this is now ready for review. I tested this locally with a TSAN build and it no longer leaks when commenting [this line](https://hg.mozilla.org/mozilla-central/file/tip/mozglue/build/TsanOptions.cpp#l312) to suppress the .. suppression.

2020-12-04 17:06 UTC, badboy commented on glean-core/rlb/src/dispatcher/global.rs
>  pub fn try_shutdown() -> Result<(), DispatchError> {
Should this be renamed to `shutdown`? We're not only trying anymore, we're actively waiting for it to shutdown.

2020-12-07 08:31 UTC, badboy requested changes

2020-12-07 08:31 UTC, badboy commented on glean-core/rlb/src/dispatcher/global.rs
> +    let _ = shutdown();
I can't comment on the lines below (damn you, github!), but line 92 (comment) is now kinda wrong and the code could be simplified I think.
As the worker thread is already `join`ed on, it's correctly shut down. I _think_ we don't even need the `mem::replace` anymore and a simple `*lock = new_dispatcher` should work now instead.

2020-12-07 09:30 UTC, badboy approved these changes

2020-12-07 09:31 UTC, merged