Bug 1698800 - Conform datetime metric reference page to new format
mozilla/glean pull request #1611
Opened 2021-04-30 16:08 UTC by brizental

...and Add Glean.js information to datetime metric page.

I also found a bug in the Swift example and fixed it (thanks @travis79 !).

[Rendered](https://innate-earth.surge.sh/reference/metrics/datetime.html).

Somethings I noticed:

- Java and Kotlin don't have the `testGetValue` API documented, was that on purpose? [That API seems to exist](https://github.com/mozilla/glean/blob/main/glean-core/android/src/main/java/mozilla/telemetry/glean/private/DatetimeMetricType.kt#L185). I can just include the missing examples in this PR, but wanted to double check first.
- Firefox Desktop `testGetValue` actually works like the `testGetValueAsString`. Worth filing a bug or was this on purpose?

2021-04-30 17:00 UTC, mdboom approved these changes
This looks great.  It seems like the missing languages for testGetValue is just an oversight so we should put that in.

As for the Firefox Desktop question, I defer to @chutten .

2021-05-03 17:41 UTC, chutten commented
>     * Firefox Desktop `testGetValue` actually works like the `testGetValueAsString`. Worth filing a bug or was this on purpose?

Just because it was on purpose doesn't mean it doesn't need a bug : )

Hm, but to know for certain whether or not this was intentional we must ask the person responsible for implementing the API. Now [who was that](https://bugzilla.mozilla.org/show_bug.cgi?id=1673643)....  : D

At the very least we should consider this approach, and a bug could serve as documentation for why we choose to do it or not. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1709147 for that purpose. Thank you for bringing this up!

2021-05-05 09:22 UTC, badboy requested changes

2021-05-05 09:22 UTC, badboy commented on docs/user/reference/metrics/datetime.md
> +Gets number of errors recorded for a given counter metric.
```suggestion
Get number of errors recorded for a given datetime metric.
```

2021-05-05 09:22 UTC, badboy commented on docs/user/reference/metrics/datetime.md
> +Gets the recorded value for a given datetime metric an [ISO Date String](https://en.wikipedia.org/wiki/ISO_8601#Dates).
```suggestion
Get the recorded value for a given datetime metric as an [ISO Date String](https://en.wikipedia.org/wiki/ISO_8601#Dates).
```

2021-05-05 09:22 UTC, badboy commented on docs/user/reference/metrics/datetime.md
> +Gets the recorded value for a given datetime metric as a language specific Date object.
```suggestion
Get the recorded value for a given datetime metric as a language-specific Date object.
```

2021-05-05 09:45 UTC, badboy commented on docs/user/reference/metrics/datetime.md
> +import org.mozilla.yourApplication.GleanMetrics.Install
```suggestion
import mozilla.telemetry.glean.testing.ErrorType
import org.mozilla.yourApplication.GleanMetrics.Install
```

2021-05-05 09:45 UTC, badboy commented on docs/user/reference/metrics/datetime.md
> +import org.mozilla.yourApplication.GleanMetrics.Install;
```suggestion
import mozilla.telemetry.glean.testing.ErrorType
import org.mozilla.yourApplication.GleanMetrics.Install;
```

2021-05-12 08:16 UTC, merged