Add documentation for tags
mozilla/glean pull request #1849
Opened 2021-11-01 19:20 UTC by wlach

See: https://github.com/mozilla/glean_parser/pull/406

2021-11-02 10:14 UTC, brizental requested changes
Hey Will, would you mind also adding the `tags` optional paramenter to the list over on the metrics.yaml reference page https://mozilla.github.io/glean/book/reference/yaml/metrics.html#optional-parameters. Might be good to also add it to the example there.

2021-11-02 10:14 UTC, brizental commented on docs/user/reference/yaml/tags.md
> +> Although we refer to pings definitions YAML files as `pings.yaml` throughout Glean documentation
```suggestion
> Although we refer to tags definitions YAML files as `tags.yaml` throughout Glean documentation
```

2021-11-02 10:39 UTC, badboy requested changes

2021-11-02 14:21 UTC, wlach commented on docs/user/reference/yaml/tags.md
> +Tag names are the top-level keys on pings definitions files.
I'll see if I can't clean things up here a bit.

2021-11-02 16:28 UTC, wlach commented
> Hey Will, would you mind also adding the `tags` optional paramenter to the list over on the metrics.yaml reference page https://mozilla.github.io/glean/book/reference/yaml/metrics.html#optional-parameters. Might be good to also add it to the example there.

Great idea! Done

2021-11-02 16:47 UTC, brizental approved these changes

2021-11-02 16:47 UTC, brizental commented on docs/user/reference/yaml/pings.md
> +Must correspond to an entry specified in a [tags file](./tags.md).
Didn't realize pings could also be tagged. That is nice.

2021-11-03 13:46 UTC, badboy approved these changes
One last thing, but then we can land it.

2021-11-03 13:46 UTC, badboy commented on docs/user/reference/yaml/metrics.md
> +#### `tags`
This is not a top-level parameter, but under the `metadata` parameter. To avoid confusion we should call this out here.

2021-11-03 13:46 UTC, badboy commented on docs/user/reference/yaml/pings.md
> +#### `tags`
As above.

2021-11-03 14:21 UTC, badboy commented
No idea why CI failed. I'll merge this, it's docs only anyway.

2021-11-03 14:21 UTC, merged