added glam related notes to integrating-glean-for-product-managers.md
mozilla/glean pull request #1950
Opened 2022-02-02 15:27 UTC by alekhyamoz

The PR related to the glam [issue](https://github.com/mozilla/glam/issues/1550)
Added notes detailing next steps required to onboard Glean apps to GLAM

2022-02-02 16:09 UTC, travis79 approved these changes
Thanks for doing this!

2022-02-08 15:39 UTC, badboy requested changes

2022-02-08 15:39 UTC, badboy commented on docs/user/user/integrating-glean-for-product-managers.md
> +To use GLAM for analysis of your application's data [file a ticket in the GLAM repository](https://github.com/mozilla/glam/issues/new/choose) with the following information:
Can we add a template to the GLAM repository?
That is: copy https://github.com/mozilla/glam/blob/main/.github/ISSUE_TEMPLATE/bug_report.md to something like `add_to_glam.md` and have the teplate ask for that info?

2022-02-08 15:39 UTC, badboy commented on docs/user/user/integrating-glean-for-product-managers.md
> +A data engineer from GLAM team will reach out to you if further information is required.
```suggestion
A data engineer from the GLAM team will reach out to you if further information is required.
```

2022-02-08 16:39 UTC, alekhyamoz commented on docs/user/user/integrating-glean-for-product-managers.md
> +2. Dataset location
Removed the section. As the information is being requested in the template

2022-02-09 09:26 UTC, badboy approved these changes

2022-02-09 09:26 UTC, merged