Use single-quote to ensure code is valid when executed on Windows
mozilla/glean pull request #2193
Opened 2022-09-19 08:54 UTC by badboy

Should fix https://github.com/mozilla-mobile/fenix/issues/27053

2022-09-19 09:09 UTC, Dexterp37 requested changes

2022-09-19 09:09 UTC, Dexterp37 commented on gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
>          current_ver = found_version.split(".")
I think we need to change this as well.

2022-09-19 09:09 UTC, Dexterp37 commented
Fixes mozilla-mobile/fenix#27053

2022-09-19 12:56 UTC, Dexterp37 approved these changes
I just tested this on my Windows machine within A-C. This works for me!

2022-09-19 13:26 UTC, merged

2022-09-26 07:35 UTC, sv-ohorvath commented
Do you have an estimate of when this will land on Fenix?

2022-09-26 10:48 UTC, Dexterp37 commented
> @badboy Do you have an estimate of when this will land on Fenix?

We need to cut a new release. This will likely happen next week as this week we're at a company wide meeting.

2022-10-06 05:33 UTC, sum20156 commented
@Dexterp37 when it will be done

2022-10-06 06:27 UTC, ioanarusiczki commented
@Dexterp37 I tried yesterday to make a build for AMO stage addon installs - > debug variant, I still get this error

2022-10-06 07:45 UTC, Dexterp37 commented
> @Dexterp37 when it will be done

@sum20156 a new release was cut yesterday and it's now being picked up by the products using Glean.

> @Dexterp37 I tried yesterday to make a build for AMO stage addon installs - > debug variant, I still get this error

@ioanarusiczki what's the specific product and steps to reproduce? If it's addons then it's the Glean JS SDK probably, which lives in mozilla/glean.js

2022-10-06 08:43 UTC, sum20156 commented
@Dexterp37 to reproduce..I just freshly cloned the repo...branch is main and the build variant is debug

2022-10-06 09:11 UTC, Dexterp37 commented
> @Dexterp37 to reproduce..I just freshly cloned the repo...branch is main and the build variant is debug

@sum20156 sorry for the confusion, I was asking @ioanarusiczki about how to reproduce, as their problem is likely for another product. Fenix is going to use the freshly cut Glean version soon.

2022-10-06 09:30 UTC, ioanarusiczki commented
@Dexterp37 It's the same as @sum20156 said, I cloned the repo (a while ago), yesterday I've updated the repo. 
I must change a few lines so the build would let the addon installation happen on AMO stage, it's here: 
https://github.com/mozilla/addons-frontend/pull/10021/commits/e65a006767ea2e9f21d4454ace9a386215874c5b

My variant is debug. 

I get the following errors:

![errors in AS](https://user-images.githubusercontent.com/33448286/194278234-54b566b7-a1d0-4788-b2cb-32e632787b20.png)

2022-10-06 09:46 UTC, Dexterp37 commented
Oh, I see, so it's still Fenix (sorry I was confused by what addons-frontend was).

Then the answer is the same: the latest version is getting adopted by new products. The new fix will like be in Fenix tomorrow. 

Sorry for the delay, it's been all hands + flying back so this week stuff is mostly slow.

2022-10-06 09:49 UTC, ioanarusiczki commented
@Dexterp37 No problem, thanks for the info.

2022-10-10 09:18 UTC, ioanarusiczki commented
@Dexterp37 thanks! it worked 

![epic win](https://user-images.githubusercontent.com/33448286/194834394-0f7eea64-c41a-4b4d-9448-b5b29ab9ec77.png)