Bug 1832324 - Add a and await pings in iOS
mozilla/glean pull request #2477
Opened 2023-05-22 18:19 UTC by travis79

This simply awaits the internal dispatcher which is where the pings are submitted from.

2023-05-23 08:47 UTC, badboy commented
While this might get the job done for the particular feature request, I wonder if this also exposes too much internals so to speak?
We already have `Glean.shutdown()` on the RLB, which does a bunch more, but IMO is the more appropriate API to expose.
Also the Swift dispatcher is only used for the uploader anyway, so this really just exposes waiting for upload anyway.
The shutdown API is more robust, including timeouts, etc.

what do you think?

2023-05-23 12:02 UTC, travis79 commented
> While this might get the job done for the particular feature request, I wonder if this also exposes too much internals so to speak? We already have `Glean.shutdown()` on the RLB, which does a bunch more, but IMO is the more appropriate API to expose. Also the Swift dispatcher is only used for the uploader anyway, so this really just exposes waiting for upload anyway. The shutdown API is more robust, including timeouts, etc.
> 
> what do you think?

I considered that and have no issues with exposing it through the Swift API, and I agree, it is a more robust solution. The direction I went in this PR currently was only an attempt at the simplest possible solution. 

I'll rework this exposing `shutdown()` and see how it looks.

2023-05-24 08:27 UTC, badboy requested changes
Changelog entry please.

2023-05-24 08:27 UTC, badboy commented on glean-core/ios/GleanTests/GleanTests.swift
> +        // We expect only a single ping later
Weeeell, we ignore a baseline ping, so it's more like 2 pings.

2023-05-24 13:56 UTC, badboy approved these changes

2023-05-24 13:57 UTC, merged