bug 1762859 - Silently ignore add(0) on counter and labeled_counter
mozilla/glean pull request #2623
Opened 2023-09-18 20:43 UTC by chutten

2023-09-18 20:43 UTC, chutten commented
(I'm guessing one or two of the language bindings probably have their own tests that will fail that I missed by only testing Rust and Python locally, but we'll see)

2023-09-18 20:53 UTC, travis79 approved these changes
This matches what I expect from the discussion in the Bug. r+

2023-09-19 10:08 UTC, badboy requested changes

2023-09-19 10:08 UTC, badboy commented on docs/user/reference/metrics/counter.md
> +Returns the count if data is stored.
Note that the double-spacing at line-end here was load-bearing: It enforces line breaks in the generated HTML.

2023-09-19 10:08 UTC, badboy commented on glean-core/src/metrics/counter.rs
> +                    format!("Added negative or zero value {}", amount),
```suggestion
                    format!("Added negative value {}", amount),
```

2023-09-21 13:28 UTC, merged