Revert "rollback maturin version due to breaking CI change (#2635)"
mozilla/glean pull request #2637
Opened 2023-10-04 09:41 UTC by badboy

This reverts commit f0e710d.

---

The bundling didn't play out as I hoped it would.
The PR titles are now less descriptive ("Bump the python-packages group in /glean-core/python with 1 update") and still mostly contain only a single dependency update.
Feels like reverting this thus is better.

2023-10-04 12:11 UTC, travis79 approved these changes

2023-10-04 12:17 UTC, travis79 requested changes
I approved this, but I don't see where it reverts the specific commit it says it was rolling back 🤔

2023-10-05 10:24 UTC, badboy commented
> I approved this, but I don't see where it reverts the specific commit it says it was rolling back 🤔

D'oh! I rebased, but opened the PR before that and so github picked the wrong commit as the PR title

2023-10-05 12:17 UTC, travis79 approved these changes

2023-10-05 12:20 UTC, merged