Bug 1815253 - Record what caused an RKV db load failure
mozilla/glean pull request #2677
Opened 2023-11-28 15:01 UTC by perrymcmanis144

WIP for instrumenting which RKV failure caused a new rkv to be created

2023-11-29 20:02 UTC, perrymcmanis144 commented
@badboy alright probably ready for a look just to make sure it matches your expectations while I work through test failures.

2023-12-12 09:55 UTC, badboy requested changes

2023-12-12 09:55 UTC, badboy commented on glean-core/metrics.yaml
> +      - https://bugzilla.mozilla.org/show_bug.cgi?id=todo
Needs an update here.

2023-12-12 09:55 UTC, badboy commented on glean-core/metrics.yaml
> +      The result of attempting to load the RKV database.
Should we mention here more precisely that it's only the errors and that it is not reported on successful loads?

2023-12-12 09:55 UTC, badboy commented on glean-core/src/internal_metrics.rs
> +                lifetime: Lifetime::Application,
The metrics.yaml doesn't set a lifetime, so it defaults to `ping`, which I think makes more sense? We don't want this to be sent in every subsequent metrics ping until a restart, do we?

2023-12-12 15:51 UTC, badboy approved these changes

2023-12-12 16:08 UTC, merged