Bug 1805996 - Apply malloc_size_of to most types to gather heap-allocated memory
mozilla/glean pull request #2794
Opened 2024-04-10 11:53 UTC by badboy

This is not yet complete.
It's applied for all metric types and part of the global Glean object. However it doesn't expose any method yet to get the information about the global Glean object.
Metrics are generated in user code anyway, so measuring their memory usage needs codegen.

This also doesn't measure some other memory usage:

* Rkv
* delayed ping data
* event database
* any queues to the dispatcher
* maybe more?

---

This is a first attempt at integrating `malloc_size_of` to use that in a memory reporter inside m-c.
I have PoC code for m-c using this too.
There's some things I don't like yet and probably need to reach out to folks.
One of them being `wr_malloc_size_of` being different versions on crates.io and in-tree with differing implementations.

2025-04-11 17:58 UTC, chutten requested changes

2025-04-11 17:58 UTC, chutten commented on glean-core/src/common_metric_data.rs
> +    #[ignore_malloc_size_of = "atomic integers never allocate"]
Is this a bug in `wr_malloc_size_of` that it doesn't already know and handle this?

2025-04-11 17:58 UTC, chutten commented on glean-core/src/core/mod.rs
> +    #[ignore_malloc_size_of = "TODO"]
Needs a bug number

2025-04-11 17:58 UTC, chutten commented on glean-core/src/database/mod.rs
> +        // TODO: Fill in gaps.
Needs a bug number

2025-04-11 17:58 UTC, chutten commented on glean-core/src/database/mod.rs
> +                // TODO: servo's malloc_size_of implements it for BTreeMap.
Needs a bug number.

2025-04-11 17:58 UTC, chutten commented on glean-core/src/database/mod.rs
> +        n
This is always 0, isn't it.

2025-04-11 17:58 UTC, chutten commented on glean-core/src/event_database/mod.rs
> +    Debug, Clone, Deserialize, Serialize, PartialEq, Eq, malloc_size_of_derive::MallocSizeOf,
For consistency with the other files, might as well `use` it?

2025-04-11 17:58 UTC, chutten commented on glean-core/src/metrics/labeled.rs
> +        // Copy of `MallocShallowSizeOf` implementation for `HashMap<K, V>`.
Copy from where? Cite your source (and check your license)

2025-04-11 17:58 UTC, chutten commented on glean-core/src/metrics/labeled.rs
> +        // `size_of` should only be called on the main thread to avoid double-counting.
This sounds like a very Firefox-specific concern. Is there anything we can do about this in a cross-product way?

2025-04-11 17:58 UTC, chutten commented on glean-core/src/metrics/mod.rs
> +        match self {
Guess there's no way to say "sum `MallockSizeOf::size_of` with `ops` over all tuple members, regardless of enum variant", huh. Dang.

2025-04-11 17:58 UTC, chutten commented on glean-core/src/metrics/mod.rs
> +                // Note: This is behind an `Arc`.
What is behind an `Arc`?

2025-04-11 17:58 UTC, chutten commented on glean-core/src/metrics/mod.rs
> +impl_malloc_size_of_for_metric!(CustomDistributionMetric);
So we're just gonna ignore `range_min`, `range_max`, `bucket_count`, and `histogram_type`?

Also, why does this need to be a macro? Can't we impl it over all T that are `impl MetricType`? (I guess that could conflict with the specialized versions... but we could put the default behaviour in the trait and override it in the metrictype's impl, maybe?

2025-04-11 17:58 UTC, chutten commented on glean-core/src/upload/directory.rs
> +        let shallow_size = unsafe {
Needs safety note

2025-04-11 17:58 UTC, chutten commented on glean-core/src/upload/mod.rs
> +                    unsafe { ops.malloc_enclosing_size_of(front) }
Needs safety note

2025-04-11 17:58 UTC, chutten commented on glean-core/src/upload/mod.rs
> +                // An estimate.
Needs explanation

2025-04-11 17:58 UTC, chutten commented on glean-core/src/upload/mod.rs
> +            + unsafe { ops.malloc_size_of(self.processed_pending_pings.as_ptr()) }
If this is the safety rationale, we still need it to conform to the format of other safety notes.

2025-04-14 08:53 UTC, badboy commented on glean-core/src/common_metric_data.rs
> +    #[ignore_malloc_size_of = "atomic integers never allocate"]
Well. "Bug". Just not implemented. It could be done (and I have the keys to do it!). But for now just skipping it works just as good.

2025-04-14 20:08 UTC, chutten commented on glean-core/src/common_metric_data.rs
> +    #[ignore_malloc_size_of = "atomic integers never allocate"]
Please file and reference a bug (I'm guessing from the moz.build it'd be in `Core:: Graphics: WebRender`?)

2025-04-15 10:40 UTC, badboy commented on glean-core/src/database/mod.rs
> +        n
Right now it is. Let me trim it down.

2025-04-15 10:44 UTC, badboy commented on glean-core/src/metrics/mod.rs
> +        match self {
nope

2025-04-15 10:48 UTC, badboy commented on glean-core/src/metrics/mod.rs
> +impl_malloc_size_of_for_metric!(CustomDistributionMetric);
None of the parameters you mentioned allocate.

For why it cannot be a generic impl:

```
343 | impl<T: MetricType> ::malloc_size_of::MallocSizeOf for T where T: MetricType {
    |      ^ type parameter `T` must be used as the type parameter for some local type
```

2025-04-15 15:00 UTC, chutten approved these changes
Missed a safety note, otherwise looks pretty good.

2025-04-15 15:29 UTC, badboy commented
> Missed a safety note, otherwise looks pretty good.

sorry about that!

2025-04-15 15:43 UTC, merged