bug 1892097 - New TimingDistribution API for a single duration.
mozilla/glean pull request #2809
Opened 2024-04-22 19:55 UTC by chutten

Unfortunately I can't find timing_distribution tests that have a dispatcher, so I can't test this new API. Luckily, aside from a Duration -> u128 -> u64 conversion chain, all the logic is in accumulate_raw_samples_nanos_sync which is covered.

2024-04-22 20:33 UTC, travis79 requested changes
Please add some test coverage for this, if possible

2024-04-23 07:27 UTC, Dexterp37 commented on CHANGELOG.md
> +  * New `TimingDistribution` API for single-duration accumulation. ([bug 1892097](https://bugzilla.mozilla.org/show_bug.cgi?id=1892097))
@chutten would you kindly add a _very short_ sentence about why we need this?

2024-04-24 07:36 UTC, Dexterp37 approved these changes
r+ for the changelog comment part

2024-04-24 12:47 UTC, travis79 approved these changes
Thanks for the test coverage, it was interesting to learn all the the things uncovered by way of adding it ;)

2024-04-24 13:03 UTC, merged