Bug 1918144 - Document submitting Glean events in "real-time"
mozilla/glean pull request #2953
Opened 2024-09-11 18:37 UTC by travis79

This adds some more specific documentation about Glean's ability to submit events in "real-time" (sending, not analyzing) by way of using the maximum events per ping parameter to cause Glean to send an events ping for every event recorded.

This will be augmented later once I've gotten a chance to run some experiments and measure the impacts with real data.

2024-09-11 19:25 UTC, chutten requested changes
The doc's a little slim on reasons why someone might choose to configure a Glean SDK in this way. Is this intentional, or should we write a sentence like "this, in ideal network and ingestion circumstances, can allow data to arrive within seconds-to-minutes of being recorded"

2024-09-11 19:25 UTC, chutten commented on docs/user/user/howto/real-time-events/real-time-events.md
> +real-time. There are networks to traverse, ingestion pipelines, etl, etc. that are all factors to keep in mind when considering how soon
To me the hyphenated `real-time` is an adjective, the noun is `real time`. So while there are "real-time events", those are "events sent in real time".
```suggestion
real time. There are networks to traverse, ingestion pipelines, etl, etc. that are all factors to keep in mind when considering how soon
```

2024-09-11 19:25 UTC, chutten commented on docs/user/user/howto/real-time-events/real-time-events.md
> +"Real-Time" in the context of Glean [Events](../../../reference/metrics/event.md) directly relates to configuring Glean to send each event in an [Events Ping](../../pings/events.md) as soon as it is
"This minimizes the time between instrumentation and reporting, but doesn't describe how quickly received data is made available for querying."

2024-09-11 19:25 UTC, chutten commented on docs/user/user/howto/real-time-events/real-time-events.md
> +## Configuring Glean For "Real-Time" Events
Do we want to be particular and say "the Glean SDK" throughout?

2024-09-11 19:25 UTC, chutten commented on docs/user/user/howto/real-time-events/real-time-events.md
> +real-time. There are networks to traverse, ingestion pipelines, etl, etc. that are all factors to keep in mind when considering how soon
Also, if the network is borked, we'll reliably retry.

2024-09-11 19:25 UTC, chutten commented on docs/user/user/howto/real-time-events/real-time-events.md
> +There are also other trade-offs to consider when sending event pings with each and every event. For every event recorded a network request
Might just omit this first sentence. Not sure it adds anything the structure of the document doesn't itself communicate.

2024-09-11 19:25 UTC, chutten commented on docs/user/user/howto/real-time-events/real-time-events.md
> +will be generated when the event is submitted for ingestion. By default, Glean batches up to 500 events per event ping, so this has the
Inconsistent capitalization (and pluralization) on "event ping". My personal style guide is `"events" ping`, but elsewhere in this doc you use `Events Ping`.

2024-09-12 13:28 UTC, travis79 commented
> The doc's a little slim on reasons why someone might choose to configure a Glean SDK in this way. Is this intentional, or should we write a sentence like "this, in ideal network and ingestion circumstances, can allow data to arrive within seconds-to-minutes of being recorded"

It's light on marketing details because I still have some work and measurement of impacts that I'd like to do to complete this documentation. I'd like to be able to back up any claims and potential impacts with real data. This'll be tracked in [Bug 1918149](https://bugzilla.mozilla.org/show_bug.cgi?id=1918149)

2024-09-12 14:21 UTC, chutten approved these changes

2024-09-12 14:28 UTC, merged